### ISSUE TITLE
(2005, "Unknown MySQL server host 'db' (-2)")

### ISSUE THREAD

**Issue by numbawon** [fpiesche/hercules-docker#11]
I'm getting a couple errors, but trying to solve the database host name. Error below:

hercules@a963566ad7df:/hercules$ python3 /autolycus/autolycus.py -p /hercules info
[WARN] 2021-05-29 22:11:42,030: Global config file /autolycus/autolycus_config.json does not exist.
[WARN] 2021-05-29 22:11:42,031: Install config file /hercules/conf/autolycus_config.json does not exist.
2021-05-29 22:11:42,031: Hercules  git version v2020.11.16
2021-05-29 22:11:42,031: Packet version latest
2021-05-29 22:11:42,031: renewal mode
2021-05-29 22:11:42,031: Build date 2020-11-24_18-16-55
2021-05-29 22:11:42,031: map-server status: missing (pid: 14)
2021-05-29 22:11:42,031: char-server status: missing (pid: 15)
2021-05-29 22:11:42,031: login-server status: missing (pid: 17)
2021-05-29 22:11:42,087: Database status: Unavailable
2021-05-29 22:11:42,087: Database URL: mysql://ragnarok:ragnarok@db:3306/ragnarok
2021-05-29 22:11:42,087: Database status reason: (MySQLdb._exceptions.OperationalError) (2005, "Unknown MySQL server host 'db' (-2)") (Background on this error at: http://sqlalche.me/e/13/e3q8)

Using the docker-compose as it is generally from the git, but tried several things like changing the MYSQL_SERVER: database variable to db (among other names) as it looks like that is the name in the URL that it is expecting. not sure what else to try at this point. 

Both the server container and the database containers are running but it seems the server container cannot find the database.

**Comment by numbawon** [comment]
database_1      | Version: '10.4.19-MariaDB-1:10.4.19+maria~focal'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
game_servers_1  | Traceback (most recent call last):
game_servers_1  |   File "/autolycus/autolycus.py", line 581, in <module>
game_servers_1  |     launcher.execute()
game_servers_1  |   File "/autolycus/autolycus.py", line 352, in execute
game_servers_1  |     self.args.func()
game_servers_1  |   File "/autolycus/autolycus.py", line 535, in setup_all
game_servers_1  |     self._wait_for_database()
game_servers_1  |   File "/autolycus/autolycus.py", line 347, in _wait_for_database
game_servers_1  |     raise IOError(
game_servers_1  | OSError: Database mysql://ragnarok:ragnarok@db:3306/ragnarok did not become available in time! Reason: (MySQLdb._exceptions.OperationalError) (2005, "Unknown MySQL server host 'db' (-2)") (Background on this error at: http://sqlalche.me/e/13/e3q8)
game_servers_1  | [WARN] 2021-05-30 02:28:08,196: Global config file /autolycus/autolycus_config.json does not exist.
game_servers_1  | [WARN] 2021-05-30 02:28:08,197: Install config file /hercules/conf/autolycus_config.json does not exist.
game_servers_1  | 2021-05-30 02:28:08,197: map-server is stopped, no need to stop.
game_servers_1  | 2021-05-30 02:28:08,198: char-server is stopped, no need to stop.
game_servers_1  | 2021-05-30 02:28:08,198: login-server is stopped, no need to stop.
game_servers_1  | 2021-05-30 02:28:08,198: Setting up database connection as {'db_hostname': 'db', 'db_username': 'ragnarok', 'db_password': 'ragnarok', 'db_port': '3306', 'db_database': 'ragnarok'}.
game_servers_1  | 2021-05-30 02:28:08,201: Waiting for database for up to 120 seconds...
game_servers_1  | Traceback (most recent call last):
game_servers_1  |   File "/autolycus/autolycus.py", line 581, in <module>
game_servers_1  |     launcher.execute()
game_servers_1  |   File "/autolycus/autolycus.py", line 352, in execute
game_servers_1  |     self.args.func()
game_servers_1  |   File "/autolycus/autolycus.py", line 535, in setup_all
game_servers_1  |     self._wait_for_database()
game_servers_1  |   File "/autolycus/autolycus.py", line 347, in _wait_for_database
game_servers_1  |     raise IOError(
game_servers_1  | OSError: Database mysql://ragnarok:ragnarok@db:3306/ragnarok did not become available in time! Reason: (MySQLdb._exceptions.OperationalError) (2005, "Unknown MySQL server host 'db' (-2)") (Background on this error at: http://sqlalche.me/e/13/e3q8)
ro-hurcules_game_servers_1 exited with code 1

**Comment by ghost** [comment]
Same for me. Env "MYSQL_SERVER" is ignored. Adding a network alias "db" to the database service in docker-compose can be used as workaround.
